### ISSUE TITLE
Scanner crashes when trying to associate "Krombacher Radler" barcode with user

### ISSUE THREAD

**Issue by florian-f** [flipdot/drinks-scanner#1]
How to reproduce: 

* Select user
* Press "ID Card"
* Scan Krombacher Radler barcode

After this, the barcode scanner stops working until reboot.

**Comment by cfstras** [comment]
wrong repo :) https://github.com/flipdot/drinks-scanner-display

**Comment by cfstras** [comment]
fixed https://github.com/flipdot/drinks-scanner-display/commit/101284e2afce2cd889ce480f49c3d4f692374521
